/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'oddone' at '7/14/15 11:20 AM' with Gradle 2.1
 *
 * @author oddone, @date 7/14/15 11:20 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
